# Generated by Django 5.2.12 on 2026-03-26 14:14

import i18nfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exhibition", "0002_alter_exhibitorinfo_booth_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exhibitorinfo",
            name="booth_name",
            field=i18nfield.fields.I18nCharField(
                blank=True, max_length=100, verbose_name="Booth Name"
            ),
        ),
    ]
