# Generated by Django 5.2.12 on 2026-04-21 00:00

from django.conf import settings
from django.db import migrations
import i18nfield.fields


def migrate_sponsor_group_names(apps, schema_editor):
    SponsorGroup = apps.get_model("exhibition", "SponsorGroup")

    for group in SponsorGroup.objects.select_related("event").all():
        raw_value = group.name
        data = getattr(raw_value, "data", raw_value)
        if isinstance(data, dict):
            continue
        if not data:
            continue

        locale = getattr(group.event, "locale", None) or settings.LANGUAGE_CODE
        group.name = {locale: str(data)}
        group.save(update_fields=["name"])


class Migration(migrations.Migration):
    dependencies = [
        (
            "exhibition",
            "0003_exhibitorinfo_contact_url_exhibitorinfo_header_image_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sponsorgroup",
            name="exhibition_event_sponsor_group_name_uniq",
        ),
        migrations.AlterModelOptions(
            name="sponsorgroup",
            options={"ordering": ("pk",)},
        ),
        migrations.AlterField(
            model_name="sponsorgroup",
            name="name",
            field=i18nfield.fields.I18nCharField(
                max_length=120,
                verbose_name="Group Name",
            ),
        ),
        migrations.RunPython(
            migrate_sponsor_group_names,
            migrations.RunPython.noop,
        ),
    ]
