# Generated by Django 5.2.12 on 2026-04-21 00:00

import i18nfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "exhibition",
            "0003_exhibitorinfo_contact_url_exhibitorinfo_header_image_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sponsorgroup",
            options={"ordering": ("level", "pk")},
        ),
        migrations.AddField(
            model_name="sponsorgroup",
            name="level",
            field=models.PositiveIntegerField(
                db_index=True,
                default=1,
                verbose_name="Level",
            ),
        ),
        migrations.AlterField(
            model_name="sponsorgroup",
            name="name",
            field=i18nfield.fields.I18nCharField(
                max_length=120,
                verbose_name="Group Name",
            ),
        ),
    ]
