# Generated by OpenCode on 2026-06-11

import django.db.models.deletion
import i18nfield.fields
from django.conf import settings
from django.db import migrations, models

import exhibition.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exhibition", "0004_sponsorgroup_i18n_name_and_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibitorsettings",
            name="call_deadline",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Submission deadline",
            ),
        ),
        migrations.AddField(
            model_name="exhibitorsettings",
            name="call_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="exhibitorsettings",
            name="call_headline",
            field=i18nfield.fields.I18nCharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Call headline",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exhibitorsettings",
            name="call_hide_after_deadline",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="exhibitorsettings",
            name="call_text",
            field=i18nfield.fields.I18nTextField(
                blank=True,
                default="",
                verbose_name="Call text",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ExhibitionQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variant",
                    models.CharField(
                        choices=[
                            ("string", "Text (one-line)"),
                            ("text", "Multi-line text"),
                            ("url", "URL"),
                            ("boolean", "Confirmation"),
                            ("choices", "Radio button (Choose one option)"),
                            (
                                "multiple_choice",
                                "Checkbox (Choose one or several options)",
                            ),
                            ("select", "Select (one option)"),
                        ],
                        default="string",
                        max_length=32,
                    ),
                ),
                (
                    "question",
                    i18nfield.fields.I18nCharField(
                        max_length=800,
                        verbose_name="Custom question",
                    ),
                ),
                (
                    "help_text",
                    i18nfield.fields.I18nCharField(
                        blank=True,
                        max_length=800,
                        null=True,
                        verbose_name="help text",
                    ),
                ),
                ("required", models.BooleanField(default=False, verbose_name="required")),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                ("position", models.IntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exhibition_questions",
                        to="base.event",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "id"),
            },
        ),
        migrations.CreateModel(
            name="ExhibitionProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=exhibition.models.generate_proposal_code,
                        max_length=12,
                        unique=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("submitted", "submitted"),
                            ("accepted", "accepted"),
                            ("rejected", "rejected"),
                            ("withdrawn", "withdrawn"),
                        ],
                        db_index=True,
                        default="submitted",
                        max_length=16,
                    ),
                ),
                ("name", i18nfield.fields.I18nCharField(max_length=190, verbose_name="Name")),
                (
                    "description",
                    i18nfield.fields.I18nTextField(
                        blank=True,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="URL")),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "contact_url",
                    models.URLField(blank=True, null=True, verbose_name="Contact URL"),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, null=True, verbose_name="Video URL"),
                ),
                (
                    "slides",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="exhibition-proposals/slides",
                        verbose_name="Slides",
                    ),
                ),
                (
                    "slides_url",
                    models.URLField(blank=True, null=True, verbose_name="Slides URL"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=exhibition.models.proposal_logo_path,
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(blank=True, null=True, verbose_name="Logo URL"),
                ),
                (
                    "header_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=exhibition.models.proposal_header_image_path,
                    ),
                ),
                (
                    "header_image_url",
                    models.URLField(
                        blank=True,
                        null=True,
                        verbose_name="Header Image URL",
                    ),
                ),
                ("is_sponsor", models.BooleanField(default=False)),
                ("is_exhibitor", models.BooleanField(default=True)),
                ("booth_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "booth_name",
                    i18nfield.fields.I18nCharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Booth Name",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Message to the organizers",
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Internal review notes",
                    ),
                ),
                ("submitted", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "approved_exhibitor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_proposals",
                        to="exhibition.exhibitorinfo",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exhibition_proposals",
                        to="base.event",
                    ),
                ),
                (
                    "sponsor_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposals",
                        to="exhibition.sponsorgroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exhibition_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
            },
        ),
        migrations.CreateModel(
            name="ExhibitionQuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", i18nfield.fields.I18nCharField(verbose_name="Response")),
                ("position", models.IntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="exhibition.exhibitionquestion",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "id"),
            },
        ),
        migrations.CreateModel(
            name="ExhibitionProposalSocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "network",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("flickr", "Flickr"),
                            ("github", "GitHub"),
                            ("gitlab", "GitLab"),
                            ("gitter", "Gitter"),
                            ("google_groups", "Google Groups"),
                            ("instagram", "Instagram"),
                            ("linkedin", "LinkedIn"),
                            ("mastodon", "Mastodon"),
                            ("patreon", "Patreon"),
                            ("telegram", "Telegram"),
                            ("vimeo", "Vimeo"),
                            ("vk", "VK"),
                            ("weibo", "Weibo"),
                            ("x", "X"),
                            ("xing", "Xing"),
                            ("youtube", "YouTube"),
                            ("youtube_privacy", "YouTube Privacy"),
                        ],
                        max_length=32,
                    ),
                ),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="exhibition.exhibitionproposal",
                    ),
                ),
            ],
            options={
                "ordering": ("network", "url"),
            },
        ),
        migrations.CreateModel(
            name="ExhibitionProposalExtraLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=120, verbose_name="Label")),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_links",
                        to="exhibition.exhibitionproposal",
                    ),
                ),
            ],
            options={
                "ordering": ("label", "url"),
            },
        ),
        migrations.CreateModel(
            name="ExhibitionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.TextField(blank=True)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="exhibition.exhibitionproposal",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="exhibition.exhibitionquestion",
                    ),
                ),
                (
                    "options",
                    models.ManyToManyField(
                        related_name="answers",
                        to="exhibition.exhibitionquestionoption",
                    ),
                ),
            ],
            options={
                "unique_together": {("question", "proposal")},
            },
        ),
    ]
