# Generated by Django 6.0.7 on 2026-09-20 10:28

import django.db.models.deletion
import eventyay.base.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exhibition", "0027_exhibitorinfo_sessions"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibitionquestion",
            name="dependency_question",
            field=models.ForeignKey(
                blank=True,
                help_text="This field will only be shown if the selected field has one of the specified values.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dependent_questions",
                to="exhibition.exhibitionquestion",
                verbose_name="Custom field dependency",
            ),
        ),
        migrations.AddField(
            model_name="exhibitionquestion",
            name="dependency_values",
            field=eventyay.base.models.fields.MultiStringField(
                default=list, verbose_name="Dependency values"
            ),
        ),
    ]
