# Generated by Django 6.0.8 on 2026-09-28 15:28

import django.db.models.deletion
import eventyay.base.models.base
import i18nfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0030_exhibitorinfo_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', i18nfield.fields.I18nCharField(max_length=255, verbose_name='Product name')),
                ('description', i18nfield.fields.I18nTextField(blank=True, help_text='This is shown below the product name in lists.', null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Price')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('available_from', models.DateTimeField(blank=True, help_text='This product will not be sold before the given date.', null=True, verbose_name='Available from')),
                ('available_until', models.DateTimeField(blank=True, help_text='This product will not be sold after the given date.', null=True, verbose_name='Available until')),
                ('position', models.IntegerField(default=0)),
                ('purpose', models.CharField(choices=[('exhibition', 'Exhibition'), ('sponsorship', 'Sponsorship')], default='sponsorship', max_length=16, verbose_name='Product purpose')),
                ('includes_booth', models.BooleanField(default=True, help_text='Sponsorships come with a booth unless you turn this off, for example for a purely digital package. Exhibition products always include one.', verbose_name='Includes exhibition booth')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_products', to='base.event')),
            ],
            options={
                'verbose_name': 'Exhibition product',
                'verbose_name_plural': 'Exhibition products',
                'ordering': ('position', 'id'),
            },
            bases=(models.Model, eventyay.base.models.base.LoggingMixin),
        ),
    ]
