# Generated by Django 6.0.7 on 2026-09-20 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '__first__'),
        ('exhibition', '0030_exhibitorinfo_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('exhibition', 'Exhibition'), ('sponsorship', 'Sponsorship')], default='sponsorship', max_length=16, verbose_name='Product purpose')),
                ('includes_booth', models.BooleanField(default=True, help_text='Sponsorships come with a booth unless you turn this off, for example for a purely digital package. Exhibition products always include one.', verbose_name='Includes exhibition booth')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_product', to='base.product')),
            ],
            options={
                'verbose_name': 'Exhibition product',
                'verbose_name_plural': 'Exhibition products',
                'ordering': ('product__category__position', 'product__position', 'product__pk'),
            },
        ),
    ]
