# Generated by Django 5.2.15 on 2026-10-08 11:44

import django.db.models.deletion
import eventyay.base.models.base
import i18nfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0031_exhibitionproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitionProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', i18nfield.fields.I18nCharField(max_length=255, verbose_name='Category name')),
                ('internal_name', models.CharField(blank=True, help_text='If you set this, it will be used instead of the public name in the backend.', max_length=255, verbose_name='Internal name')),
                ('description', i18nfield.fields.I18nTextField(blank=True, null=True, verbose_name='Category description')),
                ('position', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_product_categories', to='base.event')),
            ],
            options={
                'verbose_name': 'Exhibition product category',
                'verbose_name_plural': 'Exhibition product categories',
                'ordering': ('position', 'id'),
            },
            bases=(models.Model, eventyay.base.models.base.LoggingMixin),
        ),
        migrations.AddField(
            model_name='exhibitionproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='exhibition.exhibitionproductcategory', verbose_name='Category'),
        ),
    ]
