# Generated by Django 5.2.15 on 2026-10-09 13:27

import django.db.models.deletion
import eventyay.base.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0032_exhibitionproductcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, verbose_name='Order code')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='pending', max_length=16, verbose_name='Status')),
                ('name', models.CharField(max_length=255, verbose_name='Contact name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='Phone number')),
                ('total', models.DecimalField(decimal_places=2, max_digits=13, verbose_name='Total')),
                ('currency', models.CharField(max_length=10, verbose_name='Currency')),
                ('answers', models.JSONField(blank=True, default=dict, verbose_name='Order form answers')),
                ('payment_provider', models.CharField(blank=True, max_length=255, verbose_name='Payment method')),
                ('payment_reference', models.CharField(blank=True, max_length=255, verbose_name='Payment reference')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Payment date')),
                ('expires', models.DateTimeField(blank=True, null=True, verbose_name='Expiration date')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Order date')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_orders', to='base.event')),
            ],
            options={
                'verbose_name': 'Exhibition order',
                'verbose_name_plural': 'Exhibition orders',
                'ordering': ('-created', '-id'),
            },
            bases=(models.Model, eventyay.base.models.base.LoggingMixin),
        ),
        migrations.CreateModel(
            name='ExhibitionOrderPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=13, verbose_name='Price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='exhibition.exhibitionorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_positions', to='exhibition.exhibitionproduct', verbose_name='Product')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='exhibitionorder',
            constraint=models.UniqueConstraint(fields=('event', 'code'), name='exhibition_order_code_unique_per_event'),
        ),
    ]
