from django.urls import path
from eventyay.api.urls import event_router
from eventyay.common.urls import OrganizerSlugConverter  # noqa: F401

from .api import (
    ExhibitorAuthView,
    ExhibitorInfoViewSet,
    LeadCreateView,
    LeadRetrieveView,
    LeadUpdateView,
    TagListView,
    VoucherRedemptionRetrieveView,
)
from .views import (
    CallTextPreviewView,
    CustomEmailTemplateCreateView,
    CustomEmailTemplateDeleteView,
    DashboardView,
    EmailBulkActionView,
    EmailComposeView,
    EmailDeleteView,
    EmailEditView,
    EmailOutboxListView,
    EmailSendView,
    EmailSentListView,
    EmailTemplatePreviewView,
    EmailTemplatesView,
    ExhibitionDefaultFieldEditView,
    ExhibitionDefaultFieldResetView,
    ExhibitionQuestionCreateView,
    ExhibitionQuestionDeleteView,
    ExhibitionQuestionEditView,
    ExhibitionQuestionListView,
    ExhibitorCopyKeyView,
    ExhibitorCreateView,
    ExhibitorDeleteView,
    ExhibitorDeviceManageView,
    ExhibitorEditView,
    ExhibitorListView,
    ExhibitorReorderView,
    ExhibitorVoucherBulkSendView,
    ExhibitorVoucherManageView,
    ProposalActionView,
    ProposalDetailView,
    ProposalListView,
    PublicCallSecretView,
    PublicCallView,
    PublicExhibitorDetailView,
    PublicExhibitorListView,
    SettingsView,
    SponsorGroupFrontPageToggleView,
    SponsorGroupReorderView,
    SponsorReorderView,
    UserProposalCreateView,
    UserProposalEditView,
    UserProposalListView,
    UserProposalReinstateView,
    UserProposalWithdrawView,
)

urlpatterns = [
    path(
        "<str:organizer>/<str:event>/exhibition/",
        PublicExhibitorListView.as_view(),
        name="public_list",
    ),
    path(
        "<str:organizer>/<str:event>/exhibition/call/",
        PublicCallView.as_view(),
        name="public_call",
    ),
    path(
        "<str:organizer>/<str:event>/exhibition/call/s/<str:secret>/",
        PublicCallSecretView.as_view(),
        name="public_call_secret",
    ),
    path(
        "<str:organizer>/<str:event>/exhibition/call/submit/",
        UserProposalCreateView.as_view(),
        name="proposal.add",
    ),
    path(
        "<str:organizer>/<str:event>/exhibition/call/me/",
        UserProposalListView.as_view(),
        name="proposal.user_list",
    ),
    path(
        "<str:organizer>/<str:event>/exhibition/call/proposals/<str:code>/",
        UserProposalEditView.as_view(),
        name="proposal.user_edit",
    ),
    path(
        "<str:organizer>/<str:event>/exhibition/call/proposals/<str:code>/withdraw/",
        UserProposalWithdrawView.as_view(),
        name="proposal.user_withdraw",
    ),
    path(
        "<str:organizer>/<str:event>/exhibition/call/proposals/<str:code>/reinstate/",
        UserProposalReinstateView.as_view(),
        name="proposal.user_reinstate",
    ),
    path(
        "<str:organizer>/<str:event>/exhibition/<int:pk>/",
        PublicExhibitorDetailView.as_view(),
        name="public_detail",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/settings",
        SettingsView.as_view(active_tab="exhibitors"),
        name="settings",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/settings/exhibitors",
        SettingsView.as_view(active_tab="exhibitors"),
        name="settings.exhibitors",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/settings/sponsors",
        SettingsView.as_view(active_tab="sponsors"),
        name="settings.sponsors",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/settings/vouchers",
        SettingsView.as_view(active_tab="vouchers"),
        name="settings.vouchers",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/settings/call",
        SettingsView.as_view(active_tab="call"),
        name="settings.call",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/settings/call/preview",
        CallTextPreviewView.as_view(),
        name="settings.call.preview",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/settings/sponsors/groups/<int:pk>/toggle-front-page",
        SponsorGroupFrontPageToggleView.as_view(),
        name="toggle_front_page",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/settings/sponsors/groups/reorder",
        SponsorGroupReorderView.as_view(),
        name="reorder_groups",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>",
        DashboardView.as_view(),
        name="dashboard",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/exhibitors",
        ExhibitorListView.as_view(partner_type="exhibitor"),
        name="exhibitors",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/exhibitors/reorder",
        ExhibitorReorderView.as_view(),
        name="exhibitors.reorder",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/exhibitors/send-vouchers",
        ExhibitorVoucherBulkSendView.as_view(partner_type="exhibitor"),
        name="exhibitors.send_vouchers",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/sponsors",
        ExhibitorListView.as_view(partner_type="sponsor"),
        name="sponsors",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/sponsors/reorder",
        SponsorReorderView.as_view(),
        name="sponsors.reorder",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/sponsors/send-vouchers",
        ExhibitorVoucherBulkSendView.as_view(partner_type="sponsor"),
        name="sponsors.send_vouchers",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/exhibitors/add",
        ExhibitorCreateView.as_view(partner_type="exhibitor"),
        name="exhibitors.add",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/sponsors/add",
        ExhibitorCreateView.as_view(partner_type="sponsor"),
        name="sponsors.add",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/call",
        ProposalListView.as_view(),
        name="proposal.list",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/call/actions",
        ProposalActionView.as_view(),
        name="proposal.actions",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/call/proposals/<str:code>",
        ProposalDetailView.as_view(),
        name="proposal.detail",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/call/questions",
        ExhibitionQuestionListView.as_view(),
        name="call.questions",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/call/questions/add",
        ExhibitionQuestionCreateView.as_view(),
        name="call.questions.add",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/call/questions/<int:pk>/edit",
        ExhibitionQuestionEditView.as_view(),
        name="call.questions.edit",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/call/questions/<int:pk>/delete",
        ExhibitionQuestionDeleteView.as_view(),
        name="call.questions.delete",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/call/fields/<slug:key>/edit",
        ExhibitionDefaultFieldEditView.as_view(),
        name="call.fields.edit",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/call/fields/<slug:key>/reset",
        ExhibitionDefaultFieldResetView.as_view(),
        name="call.fields.reset",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/add",
        ExhibitorCreateView.as_view(),
        name="add",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/edit/<int:pk>",
        ExhibitorEditView.as_view(),
        name="edit",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/delete/<int:pk>",
        ExhibitorDeleteView.as_view(),
        name="delete",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/copy_key/<int:pk>",
        ExhibitorCopyKeyView.as_view(),
        name="copy_key",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/vouchers/<int:pk>",
        ExhibitorVoucherManageView.as_view(),
        name="vouchers",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/devices/<int:pk>",
        ExhibitorDeviceManageView.as_view(),
        name="devices",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/emails/compose",
        EmailComposeView.as_view(),
        name="email.compose",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/emails/outbox",
        EmailOutboxListView.as_view(),
        name="email.outbox",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/emails/bulk",
        EmailBulkActionView.as_view(),
        name="email.bulk",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/emails/sent",
        EmailSentListView.as_view(),
        name="email.sent",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/emails/templates",
        EmailTemplatesView.as_view(),
        name="email.templates",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/emails/templates/preview",
        EmailTemplatePreviewView.as_view(),
        name="email.templates.preview",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/emails/custom-templates/add",
        CustomEmailTemplateCreateView.as_view(),
        name="email.custom_templates.add",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/emails/custom-templates/<int:pk>/delete",
        CustomEmailTemplateDeleteView.as_view(),
        name="email.custom_templates.delete",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/emails/<int:pk>/preview",
        EmailEditView.as_view(),
        name="email.preview",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/emails/<int:pk>/edit",
        EmailEditView.as_view(),
        name="email.edit",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/emails/<int:pk>/send",
        EmailSendView.as_view(),
        name="email.send",
    ),
    path(
        "exhibitors/event/<orgslug:organizer>/<slug:event>/emails/<int:pk>/delete",
        EmailDeleteView.as_view(),
        name="email.delete",
    ),
    path(
        "api/v1/event/<str:organizer>/<str:event>/exhibitors/auth",
        ExhibitorAuthView.as_view(),
        name="exhibitor-auth",
    ),
    path(
        "api/v1/event/<str:organizer>/<str:event>/exhibitors/lead/create",
        LeadCreateView.as_view(),
        name="lead-create",
    ),
    path(
        "api/v1/event/<str:organizer>/<str:event>/exhibitors/lead/retrieve",
        LeadRetrieveView.as_view(),
        name="lead-retrieve",
    ),
    path(
        "api/v1/event/<str:organizer>/<str:event>/exhibitors/tags",
        TagListView.as_view(),
        name="exhibitor-tags",
    ),
    path(
        "api/v1/event/<str:organizer>/<str:event>/exhibitors/lead/<str:lead_id>/update",
        LeadUpdateView.as_view(),
        name="lead-update",
    ),
    path(
        "api/v1/event/<str:organizer>/<str:event>/exhibitors/vouchers/redemptions",
        VoucherRedemptionRetrieveView.as_view(),
        name="voucher-redemptions",
    ),
]

event_router.register("exhibitors", ExhibitorInfoViewSet, basename="exhibitorinfo")
